version: 0.1.{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
image: Visual Studio 2017
configuration: Debug
platform: x86
before_build:
- ps: >-
    nuget restore
    choco install opencover.portable
    choco install codecov
build:
  project: Recibos.sln
  verbosity: minimal
test_script:
- ps: >-
    OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\Users\joaos\Source\Repos\Recibos\Recibos.xUnit\bin\Debug\Recibos.xUnit.dll -noshadow" -filter:"+[Recibos.xUnit*]* -[UnitTest*]*" -output:".\Recibos_coverage.xml"
    codecov -f ".\Recibos_coverage.xml"